import { readFile, writeFile } from "fs/promises";
import { join } from "path";

/**
 * CSS Bundler for Obsidian Plugin Template
 * 
 * This script reads all CSS files from src/styles/ and merges them
 * into a single styles.css file for the plugin.
 * 
 * Add your CSS files to the cssFiles array below in dependency order.
 */

const cssDir = "./src/styles";
const outputFile = "./styles.css";

// CSS files in dependency order (base first, then components)
// Add your CSS files here
const cssFiles = [
    "base.css",
    "modals.css",
    "settings.css"
];

async function bundleCSS() {
    console.log("🎨 Bundling CSS files...");
    
    const cssContent = [
        "/*",
        " * This CSS file is automatically generated from src/styles/ by build-css.mjs",
        " * Do not edit this file directly - edit the source files in src/styles/",
        " *",
        " * This file will be included with your plugin and available in Obsidian",
        " * when your plugin is enabled.",
        " */",
        ""
    ];

    for (const file of cssFiles) {
        const filePath = join(cssDir, file);
        try {
            const content = await readFile(filePath, "utf8");
            
            // Add section separator
            cssContent.push(`/* ===== ${file.replace('.css', '').toUpperCase()} ===== */`);
            cssContent.push("");
            cssContent.push(content.trim());
            cssContent.push("");
            
            console.log(`✓ Processed ${file}`);
        } catch (error) {
            console.warn(`⚠ Warning: Could not read ${file}:`, error.message);
        }
    }

    // Write the bundled CSS
    await writeFile(outputFile, cssContent.join("\n"));
    console.log(`✅ CSS bundled successfully to ${outputFile}`);
    
    // Calculate total size
    const stats = await readFile(outputFile);
    const sizeKB = (stats.length / 1024).toFixed(1);
    console.log(`📊 Total size: ${sizeKB} KB`);
}

async function main() {
    try {
        await bundleCSS();
    } catch (error) {
        console.error("❌ CSS bundling failed:", error);
        process.exit(1);
    }
}

main();
