import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === 'production');

// Vault configuration
const DEV_VAULT = "./test-vault";
const PROD_VAULT = "./test-vault";
const PLUGIN_NAME = "obsidian-plugin-template";

const targetVault = process.env.DEV_VAULT || (prod ? PROD_VAULT : DEV_VAULT);
const pluginDir = `${targetVault}/.obsidian/plugins/${PLUGIN_NAME}`;

console.log(`\n🔨 Building for ${prod ? 'PRODUCTION' : 'DEVELOPMENT'}`);
console.log(`📂 Target: ${pluginDir}`);
if (prod) {
	console.log(`⚡ Debug code will be removed via dead code elimination\n`);
} else {
	console.log(`🐛 Debug code included\n`);
}

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ['src/main.ts'],
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtins],
	format: 'cjs',
	target: 'es2018',
	logLevel: "info",
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outfile: `${pluginDir}/main.js`,
	minify: prod,
	// Define BUILD_ENV at compile time
	// This enables dead code elimination for debug statements
	define: {
		'BUILD_ENV': prod ? '"production"' : '"development"'
	},
});

// Check for --no-watch flag
const noWatch = process.argv.includes('--no-watch');

if (prod || noWatch) {
	await context.rebuild();
	console.log("✅ Build complete!\n");
	process.exit(0);
} else {
	console.log("👁️  Watching for changes... (Press Ctrl+C to stop)\n");
	await context.watch();
}
